### PR TITLE
Fixes the issue of not downloading from the right URL for newer versions of Node.

### PR DESCRIPTION
**Pull request by snlacks**
Still works on older versions. I think this addresses: #61 #60 #58 #59 #57 

Tested installs for x64 latest, 0.12.7, 4.1.1

Thanks for the awesome tool!

### CODE REVIEW

**Comment by TimothyGu** [comment]
Duplicate of #59.

**Comment by snlacks** [comment]
Thank you TimothyGu, I thought 59 was the same issue. Fixing the prefix didn't fix downloading new versions, <4 follows has a different path. This addresses the 404 on attempts to download versions on the new path and still works on the older versions.

**Comment by yuu2lee4** [comment]
how to update my local nvmw?

**Comment by snlacks** [comment]
I haven't tested it since the last commit, but if you want to use my fork you can change my user name out for hakobera like this: 

git clone git://github.com/snlacks/nvmw.git "%HOMEDRIVE%%HOMEPATH%\.nvmw"

But, I don't know if it still works or if anyone else tested it. I don't really recommend this, there's other open issues with nvmw as well. This fix doesn't fix the path to the version installed and checks for iojs v. node in a way that doesn't result in the right one. Was updated more recently, https://github.com/coreybutler/nvm-windows

**Comment by TimothyGu** [comment]
> But, I don't know if it still works or if anyone else tested it.

As this is very similar to my PR #59 at 04fbbdfbdbf14014476ab3fabb4da345bbfb89ed, I can say that it works partially: installing Node.js/io.js works fine but installing npm only works after one try. The two other commits in #59: a7102727adb104ae7b20a28bdc850a6538ecd4ea and 4234f62783c03e6740847bd57449dda8966e5043 address the npm installation issue.

**Pull request closed without merging**
