### PR TITLE
support install with OS_ARCH

### LINKED ISSUE #40: Various architectures cannot coexist
#### Problem:

```powershell
# on x64 system

# Test 1:
nvmw install iojs-v1.2.0
nvmw use iojs-v1.2.0
iojs -p process.arch
# => x64

# Test 2:
# now install same version with x86 architecture:
nvmw install iojs-v1.2.0 x86
# you will probably notice that during the installation,
# it will ask to overwrite files when unzipping npm.zip..
nvmw use iojs-v1.2.0-x86
iojs -p process.arch
# => x64
# expected: x86

# Test 3:
# now install different version with x86 architecture
# whose x64 variant is not installed:
nvmw install iojs-v1.1.0 x86
nvmw use iojs-v1.1.0-x86
iojs -p process.arch
# => x86
```

#### Proposed solution:

* Always save with architecture slug (`-x86` or `-x64`), if the architecture is not provided in `nvmw install` on x64, still save with `-x64` prefix.
* On `nvmw use`, if `-x64` or `-x86` is provided, do not disregard it (see `Test 2` and `Test 3` in above example) and throw the error if the intended `{runtime}-{version}-{architecture}` is not installed.
* If architecture suffix is not provided, append the system default architecture slug (`-x64` on 64-bit OS).

### PR DESCRIPTION
**Pull request by fengmk2**
Fixes #40

### CODE REVIEW

**Comment by fengmk2** [comment]
I test work both on x86 and x64.
image

**Comment by am11** [comment]
@fengmk2, thanks :+1: 
I am testing your fork now. Will give you feedback shortly. :)

**Comment by am11** [comment]
@fengmk2, I tested as follow:

```cmd
nvmw install v0.10.32 x86
:: after it says 'Now using node v0.10.32'
node -v
:: returns v0.10.32
node -p process.arch
:: returns x64
```

Also getting the same result with `nvmw install v0.10.32 ia32`.

Expected behaviour:

```cmd
nvmw install v0.10.32 x86  :: and / or ia32
:: should say 'Now using node v0.10.32-x86' (and / or v0.10.32-ia32)
node -v
:: v0.10.32
node -p process.arch
:: should return ia32
```

**Comment by fengmk2** [comment]
fix x86 on https://github.com/fengmk2/nvmw/commit/6fb30026dd62b6b9055fde0ee52624ace6573d76

**Comment by am11** [comment]
@fengmk2, thank you! It now downloads ia32 binaries with either of those switches. Also tested with iojs! :+1: 

Would it be possible to make both architectures of same version co-exits? Meaning it always create a folder with arch slug: `.nvmw\v0.10.33-x64` and `.nvmw\v0.10.33-x32`. Currently it overwrites the existing folder regardless of the fact they differ in architecture.

IMO, even if you are re-downloading the existing `{version}-{arch}` it should error: `already exists, please uninstall {this version} before reinstalling to overwrite`.

**Comment by fengmk2** [comment]
Install both x32 and x64 at some time is too complex.
The most common, I think people using only one arch.

**Comment by am11** [comment]
In our use-case for example: https://github.com/sass/node-sass/issues/655, where we are building binaries for a matrix covering various runtimes are architectures, it is required to have both architectures. Having both architectures simultaneously will prevent us from reinstalling the same version again.

**Comment by fengmk2** [comment]
@am11 OK, let's change to this:

- if given arch not equal to system default arch, save node to `v0.10.33-$custom-arch`
- if given arch equal to system default arch, save node to `v0.10.33`

This change can be keep compatible.

**Comment by fengmk2** [comment]
@am11 done

**Comment by fengmk2** [comment]
@am11 you can take a try to pre build binary using https://github.com/mapbox/node-pre-gyp

**Comment by fengmk2** [comment]
image

**Comment by am11** [comment]
@fengmk2, I can confirm that it is fixed! Thank you! :+1:  :tada: 

Also thanks for the node-pre-gyp tip. We already have that planned for quite sometime: https://github.com/sass/node-sass/issues/56. We are struggling with Linux binaries which requires a lot of extra work to support older versions of CentOS (see https://github.com/sass/node-sass/issues/517 and https://github.com/sass/node-sass/issues/602). Hence automated build is not a very smooth option to implement for now.

**Comment by fengmk2** [comment]
@am11 add. 

@hakobera can review and merge now.

**Comment by hakobera** [comment]
@fengmk2 Wow, you did great work again and again! :+1:

**Pull request merged**
