### PR TITLE
installing npm from github

### PR DESCRIPTION
**Pull request by deepak1556**
This is a lame hack, but for the time being it helps ;)

### CODE REVIEW

**Comment by hakobera** [comment]
@deepak1556 Sorry, for too late reply. Your code is greate!

@fengmk2 Can you access to  https://github.com/npm/npm/archive?
This PR remove `NVMW_NODEJS_ORG_MIRROR` option to download npm.
If you are OK, I want to merge this PR.

**Comment by fengmk2** [comment]
Not OK, we should keep custom mirror optional always.

**Comment by fengmk2** [comment]
Why not add a DOWNLOAD_FROM_MIRROR options?

**Comment by fengmk2** [comment]
I will modified this pr to support custom mirror url. Please wait for my new pull request.

**Comment by deepak1556** [comment]
@fengmk2 you might wanna consider adding iojs support too :)

**Comment by fengmk2** [comment]
yep, I will add iojs support follow the nvm apis.

    $ nvmw install iojs/lateat
    $ nvmw install iojs/1.0.1

**Comment by fengmk2** [comment]
@deepak1556 @hakobera io.js support here https://github.com/hakobera/nvmw/pull/36

**Pull request closed without merging**
